home:
  path: /
  controller:   App\Controller\HomeController::index
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
property:
  path: /
  controller:   App\Controller\PropertyController::index
